version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234567890
    ports:
      - "3307:3306"
    networks:
      - hospital-network

  web-app:
    build:
      context: ./Web
      dockerfile: Dockerfile
    container_name: web-app
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/hospital_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234567890
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
