name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

  

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: spring/multi-module
          IMAGE_TAG: latest
        run: |
          docker-compose build spring/multi-module ./hospital
          docker tag spring/multi-module:latest 654654608593.dkr.ecr.ap-south-1.amazonaws.com/spring/multi-module:latest
          docker push 654654608593.dkr.ecr.ap-south-1.amazonaws.com/spring/multi-module:latest
